export const FETCH_STATIONS_REQUEST = "FETCH_STATIONS_REQUEST";
export const FETCH_STATIONS_SUCCESS = "FETCH_STATIONS_SUCCESS";
export const FETCH_STATIONS_FAILURE = "FETCH_STATIONS_FAILURE";

export const UPDATE_STATION_REQUEST = "UPDATE_STATION_REQUEST";
export const UPDATE_STATION_SUCCESS = "UPDATE_STATION_SUCCESS";
export const UPDATE_STATION_FAILURE = "UPDATE_STATION_FAILURE";
