export const FETCH_PENDING_CHANGES_REQUEST = "FETCH_PENDING_CHANGES_REQUEST";
export const FETCH_PENDING_CHANGES_SUCCESS = "FETCH_PENDING_CHANGES_SUCCESS";
export const FETCH_PENDING_CHANGES_FAILURE = "FETCH_PENDING_CHANGES_FAILURE";

export const VOTE_PENDING_CHANGE_REQUEST = "VOTE_PENDING_CHANGE_REQUEST";
export const VOTE_PENDING_CHANGE_SUCCESS = "VOTE_PENDING_CHANGE_SUCCESS";
export const VOTE_PENDING_CHANGE_FAILURE = "VOTE_PENDING_CHANGE_FAILURE";
